[package]
name = "websocket-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.0", features = ["full"] }
tokio-tungstenite = "0.27.0"
tungstenite = "0.27.0"
futures = "0.3.31"
